<x-layouts.portal title="{{ $rpp ? 'Edit RPP' : 'Buat RPP' }}" portalLabel="Portal Guru" breadcrumb="{{ $rpp ? 'Edit RPP' : 'Buat RPP' }}">
    <header class="portal-page-header"><div><p class="school-index">Perangkat Pembelajaran</p><h1 class="text-heading ui-page-title">{{ $rpp ? 'Edit RPP' : 'Buat RPP Baru' }}</h1><p class="mt-2 text-theme-sm text-muted">Pilih mapel dan kelas dari penugasan aktif Anda.</p></div><a href="{{ route('guru.rpp.index') }}" class="btn btn-outline text-theme-sm font-medium">Kembali</a></header>
    @if(session('success'))<div class="mb-5 rounded-xl border border-success-line bg-success-soft p-4 text-theme-sm text-success-ink">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="mb-5 rounded-xl border border-danger-line bg-danger-soft p-4 text-theme-sm text-danger-ink"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    @if(! $rpp)
        <section class="ui-card mb-6 rounded-2xl p-5"><h2 class="text-heading ui-form-title">Buat draft dengan AI</h2><p class="mt-1 text-theme-sm text-muted">Unggah foto materi, lalu tinjau dan edit hasil draft sebelum disimpan.</p><form class="mt-4 flex flex-wrap items-end gap-3" method="POST" action="{{ route('guru.rpp.ai-draft') }}" enctype="multipart/form-data">@csrf<div><label class="mb-1 block ui-form-label">Foto materi</label><input class="form-input text-theme-sm font-normal" type="file" name="foto_materi" accept="image/jpeg,image/png,image/webp" required></div><button class="btn btn-outline text-theme-sm font-medium" type="submit">Buat Draft AI</button></form></section>
    @endif

    <form class="ui-card rounded-2xl p-5 sm:p-6" method="POST" action="{{ $rpp ? route('guru.rpp.update', $rpp) : route('guru.rpp.store') }}" enctype="multipart/form-data" x-data="{ method: '{{ old('input_method', $rpp?->input_method ?? ($draft ? 'ai' : 'manual')) }}' }">
        @csrf @if($rpp) @method('PUT') @endif
        @if(! $rpp)<div class="mb-5"><label class="mb-1 block text-body ui-form-label">Cara membuat</label><select class="form-input text-theme-sm font-normal" name="input_method" x-model="method"><option value="manual">Tulis manual</option><option value="ai">Draft AI (sudah ditinjau)</option><option value="upload">Unggah PDF RPP</option></select></div>@else<input type="hidden" name="input_method" value="{{ $rpp->input_method }}">@endif
        <div class="grid gap-4 md:grid-cols-2">
            <div><label class="mb-1 block ui-form-label">Mapel dan Kelas</label><select class="form-input text-theme-sm font-normal" name="diniyyah_class_subject_id" required><option value="">-- Pilih penugasan --</option>@foreach($assignments as $assignment)<option value="{{ $assignment->diniyyah_class_subject_id }}" @selected(old('diniyyah_class_subject_id', $rpp?->diniyyah_class_subject_id) == $assignment->diniyyah_class_subject_id)>{{ $assignment->classSubject?->subject?->name }} — {{ $assignment->classSubject?->classroomTerm?->name }}</option>@endforeach</select></div>
            <div><label class="mb-1 block ui-form-label">Nomor RPP</label><input class="form-input text-theme-sm font-normal" name="no_rpp" value="{{ old('no_rpp', $rpp?->no_rpp) }}" maxlength="50"></div>
            <div><label class="mb-1 block ui-form-label">Tanggal pengesahan</label><input class="form-input text-theme-sm font-normal" type="date" name="tanggal_pengesahan" value="{{ old('tanggal_pengesahan', optional($rpp?->tanggal_pengesahan)->format('Y-m-d') ?? now()->toDateString()) }}"></div>
        </div>
        <div class="mt-5 rounded-xl border border-warning-line bg-warning-soft p-4" x-show="method === 'upload'"><label class="mb-1 block text-warning-ink ui-form-label">PDF RPP</label><input class="form-input text-theme-sm font-normal" type="file" name="file" accept="application/pdf"><p class="mt-1 text-theme-xs text-warning-ink font-normal">PDF maksimal 10 MB. RPP unggahan tersimpan sebagai dokumen asli dan tidak diedit secara terstruktur.</p></div>
        <div x-show="method !== 'upload'" class="mt-5 space-y-4">
            <div><label class="mb-1 block ui-form-label">Materi</label><input class="form-input text-theme-sm font-normal" name="materi" value="{{ old('materi', $rpp?->materi ?? $draft['materi'] ?? '') }}"></div>
            <div><label class="mb-1 block ui-form-label">Alokasi waktu</label><input class="form-input text-theme-sm font-normal" name="alokasi_waktu" value="{{ old('alokasi_waktu', $rpp?->alokasi_waktu ?? $draft['alokasi_waktu'] ?? '') }}" placeholder="Contoh: 2 x 35 menit"></div>
            <div><label class="mb-1 block ui-form-label">Tujuan pembelajaran</label><textarea class="form-input min-h-28 text-theme-sm font-normal" name="tujuan_pembelajaran">{{ old('tujuan_pembelajaran', $rpp?->tujuan_pembelajaran ?? $draft['tujuan_pembelajaran'] ?? '') }}</textarea></div>
            @php($meetings = old('meetings', $rpp?->meetings?->map(fn($m) => ['isi_kegiatan' => $m->isi_kegiatan, 'tanggal_kbm' => optional($m->tanggal_kbm)->format('Y-m-d')])->all() ?? $draft['meetings'] ?? [['isi_kegiatan' => '', 'tanggal_kbm' => '']]))
            <div><label class="mb-2 block ui-form-label">Kegiatan pembelajaran</label>@foreach($meetings as $i => $meeting)<div class="mb-3 rounded-xl border border-line p-3"><label class="text-muted ui-form-label">Pertemuan {{ $i + 1 }}</label><textarea class="form-input mt-1 text-theme-sm font-normal" name="meetings[{{ $i }}][isi_kegiatan]">{{ $meeting['isi_kegiatan'] ?? '' }}</textarea><input class="form-input mt-2 text-theme-sm font-normal" type="date" name="meetings[{{ $i }}][tanggal_kbm]" value="{{ $meeting['tanggal_kbm'] ?? '' }}"></div>@endforeach</div>
            <div class="grid gap-4 md:grid-cols-3"><div><label class="mb-1 block ui-form-label">Pengetahuan</label><textarea class="form-input text-theme-sm font-normal" name="pengetahuan">{{ old('pengetahuan', $rpp?->assessment?->pengetahuan ?? $draft['pengetahuan'] ?? '') }}</textarea></div><div><label class="mb-1 block ui-form-label">Keterampilan</label><textarea class="form-input text-theme-sm font-normal" name="keterampilan">{{ old('keterampilan', $rpp?->assessment?->keterampilan ?? $draft['keterampilan'] ?? '') }}</textarea></div><div><label class="mb-1 block ui-form-label">Sikap</label><textarea class="form-input text-theme-sm font-normal" name="sikap">{{ old('sikap', $rpp?->assessment?->sikap ?? $draft['sikap'] ?? '') }}</textarea></div></div>
        </div>
        <div class="mt-6 flex justify-end"><button class="btn btn-primary text-theme-sm font-medium" type="submit">{{ $rpp ? 'Simpan perubahan' : 'Simpan RPP' }}</button></div>
    </form>
</x-layouts.portal>
