<x-layouts.portal title="{{ $rpp->materi }}" portalLabel="Portal Guru" breadcrumb="RPP / {{ $rpp->materi }}">
    <header class="portal-page-header"><div><p class="school-index">Perangkat Pembelajaran</p><h1 class="text-slate-900">{{ $rpp->materi }}</h1><p class="mt-2 text-sm text-slate-500">{{ $rpp->classSubject?->subject?->name }} · {{ $rpp->classSubject?->classroomTerm?->name }}</p>@if($rpp->legacy_source_id)<p class="mt-2 text-xs font-bold text-emerald-700">Disinkron dari Project RPP · {{ $rpp->source_synced_at?->diffForHumans() }}</p>@endif</div><a href="{{ route('guru.rpp.index') }}" class="btn btn-outline">Kembali</a></header>
    @if(session('success'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{{ session('success') }}</div>@endif
    <section class="ui-card rounded-2xl p-5 sm:p-6">
        <div class="flex flex-wrap gap-2 border-b border-slate-200 pb-5"><a class="btn btn-outline btn-sm" href="{{ route('guru.rpp.export', [$rpp, 'pdf']) }}">Unduh PDF</a><a class="btn btn-outline btn-sm" href="{{ route('guru.rpp.export', [$rpp, 'png']) }}">Unduh PNG</a><a class="btn btn-outline btn-sm" href="{{ route('guru.rpp.export', [$rpp, 'docx']) }}">Unduh DOCX</a><a class="btn btn-primary btn-sm" href="{{ route('guru.rpp.share', [$rpp, 'pdf']) }}">Bagikan WhatsApp</a>@if($canManage && $rpp->isStructured())<a class="btn btn-outline btn-sm" href="{{ route('guru.rpp.edit', $rpp) }}">Edit</a>@endif</div>
        <dl class="mt-5 grid gap-4 md:grid-cols-2"><div><dt class="text-xs font-black uppercase text-slate-500">Nomor RPP</dt><dd>{{ $rpp->no_rpp ?: '—' }}</dd></div><div><dt class="text-xs font-black uppercase text-slate-500">Alokasi waktu</dt><dd>{{ $rpp->alokasi_waktu ?: '—' }}</dd></div><div class="md:col-span-2"><dt class="text-xs font-black uppercase text-slate-500">Tujuan pembelajaran</dt><dd class="mt-1 whitespace-pre-line">{{ $rpp->tujuan_pembelajaran ?: 'Dokumen PDF unggahan.' }}</dd></div></dl>
        @if($rpp->files->isNotEmpty())<div class="mt-6"><h2 class="font-black">Berkas unggahan</h2>@foreach($rpp->files as $file)<a class="mt-2 inline-block text-emerald-700 underline" href="{{ route('guru.rpp.file', [$rpp, $file]) }}">{{ $file->nama_file }}</a>@endforeach</div>@endif
        @if($rpp->isStructured())<div class="mt-6"><h2 class="font-black">Kegiatan Pembelajaran</h2>@foreach($rpp->meetings as $meeting)<article class="mt-3 rounded-xl bg-slate-50 p-4"><p class="font-bold">Pertemuan {{ $meeting->urutan }}</p><p class="mt-1 whitespace-pre-line">{{ $meeting->isi_kegiatan }}</p></article>@endforeach</div><div class="mt-6 grid gap-3 md:grid-cols-3"><div class="rounded-xl border p-4"><strong>Pengetahuan</strong><p class="mt-1 whitespace-pre-line">{{ $rpp->assessment?->pengetahuan }}</p></div><div class="rounded-xl border p-4"><strong>Keterampilan</strong><p class="mt-1 whitespace-pre-line">{{ $rpp->assessment?->keterampilan }}</p></div><div class="rounded-xl border p-4"><strong>Sikap</strong><p class="mt-1 whitespace-pre-line">{{ $rpp->assessment?->sikap }}</p></div></div>@endif
        @if($canManage)<form class="mt-6" method="POST" action="{{ route('guru.rpp.destroy', $rpp) }}" onsubmit="return confirm('Pindahkan RPP ke sampah?')">@csrf @method('DELETE')<button class="btn btn-outline btn-sm text-red-700" type="submit">Pindahkan ke Sampah</button></form>@endif
    </section>
</x-layouts.portal>
