<x-layouts.portal title="Rekap Penggajian JP" portalLabel="Portal Admin" breadcrumb="Rekap Penggajian JP">
    @php
        $query = ['academic_term_id' => $report['term']->id, 'month' => $report['month'], 'year' => $report['year']];
        $monthName = \Carbon\Carbon::create()->month($report['month'])->translatedFormat('F');
    @endphp
    <div class="space-y-6">
        @if ($errors->any())
            <div class="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-800">{{ $errors->first() }}</div>
        @endif
        @if (session('success'))
            <div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{{ session('success') }}</div>
        @endif
        <header class="flex flex-col gap-5 rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-sm lg:flex-row lg:items-end lg:justify-between">
            <div><p class="text-[11px] font-black uppercase tracking-[.16em] text-amber-600">Penggajian guru</p><h1 class="mt-1 text-3xl font-black tracking-tight text-slate-900">Rekap JP Bulanan</h1><p class="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Seluruh guru berakun tampil, termasuk yang belum memiliki jadwal atau jurnal. Tafsir serentak dihitung satu JP per sesi.</p></div>
            <div class="grid gap-2 sm:grid-cols-2 lg:min-w-80"><a href="{{ route('admin.monthly-jp-recap.export', ['format' => 'xlsx'] + $query) }}" class="inline-flex items-center justify-center rounded-xl bg-emerald-700 px-4 py-3 text-sm font-black text-white hover:bg-emerald-800">Unduh Excel</a><a href="{{ route('admin.monthly-jp-recap.export', ['format' => 'pdf'] + $query) }}" class="inline-flex items-center justify-center rounded-xl bg-rose-600 px-4 py-3 text-sm font-black text-white hover:bg-rose-700">Unduh PDF</a></div>
        </header>
        <section class="rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
            <form method="GET" class="grid gap-4 md:grid-cols-4">
                <label><span class="text-xs font-bold text-slate-600">Periode ajaran</span><select name="academic_term_id" class="form-input mt-1 bg-white">@foreach($terms as $term)<option value="{{ $term->id }}" @selected($term->id === $report['term']->id)>{{ $term->academicYear?->name }} - {{ $term->name }}</option>@endforeach</select></label>
                <label><span class="text-xs font-bold text-slate-600">Bulan</span><select name="month" class="form-input mt-1 bg-white">@for($value = 1; $value <= 12; $value++)<option value="{{ $value }}" @selected($value === $report['month'])>{{ \Carbon\Carbon::create()->month($value)->translatedFormat('F') }}</option>@endfor</select></label>
                <label><span class="text-xs font-bold text-slate-600">Tahun</span><input name="year" type="number" min="2020" max="2100" value="{{ $report['year'] }}" class="form-input mt-1 bg-white"></label>
                <div class="flex items-end"><button class="btn btn-primary w-full md:w-auto">Tampilkan laporan</button></div>
            </form>
        </section>
        <section class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs font-bold text-slate-500">Total guru</p><p class="mt-2 text-3xl font-black">{{ $report['stats']['total_teachers'] }}</p></div><div class="rounded-2xl border border-amber-200 bg-amber-50 p-4 shadow-sm"><p class="text-xs font-bold text-amber-700">Sesi Tafsir</p><p class="mt-2 text-3xl font-black text-amber-900">{{ $report['stats']['total_tafsir'] }}</p></div><div class="rounded-2xl border border-slate-800 bg-slate-900 p-4 shadow-sm"><p class="text-xs font-bold text-slate-300">JP terealisasi</p><p class="mt-2 text-3xl font-black text-white">{{ $report['stats']['total_jp'] }}</p></div><div class="rounded-2xl border border-rose-200 bg-rose-50 p-4 shadow-sm"><p class="text-xs font-bold text-rose-700">Jurnal kosong</p><p class="mt-2 text-3xl font-black text-rose-900">{{ $report['stats']['total_missing'] }}</p></div></section>
        <section class="overflow-hidden rounded-[1.75rem] border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-5"><h2 class="text-xl font-black">Rekap JP {{ $monthName }} {{ $report['year'] }}</h2></div><div class="overflow-x-auto"><table class="min-w-[1200px] w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50"><tr><th class="p-3 text-left">Guru</th><th class="p-3 text-left">Kelas / Mapel</th><th class="p-3 text-right">Asli</th><th class="p-3 text-right">Pengganti</th><th class="p-3 text-right">Tafsir</th><th class="p-3 text-right">JP</th><th class="p-3 text-right">Kosong</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($report['teachers'] as $row)<tr><td class="p-3 font-bold">{{ $row['name'] }}<span class="block text-xs font-normal text-slate-500">{{ $row['niy'] ?: '-' }} · {{ $row['status'] ?: '-' }}</span></td><td class="p-3">{{ implode(', ', $row['classes']) ?: '-' }}<span class="block text-xs text-slate-500">{{ implode(', ', $row['subjects']) ?: '-' }}</span></td><td class="p-3 text-right">{{ $row['sesi_asli'] }}</td><td class="p-3 text-right">{{ $row['sesi_pengganti'] }}</td><td class="p-3 text-right">{{ $row['sesi_tafsir'] }}</td><td class="p-3 text-right font-black">{{ $row['total_jp'] }}</td><td class="p-3 text-right">{{ $row['missing_count'] }}</td></tr>@endforeach</tbody></table></div></section>
        <section class="overflow-hidden rounded-[1.75rem] border border-amber-200 bg-white shadow-sm">
            <div class="border-b border-amber-100 p-5"><p class="text-[11px] font-black uppercase tracking-[.16em] text-amber-700">Perlu persetujuan admin</p><h2 class="mt-1 text-xl font-black">Audit Tafsir Serentak</h2><p class="mt-1 text-sm text-slate-500">Jurnal lama yang cocok dengan seluruh jadwal kelas dapat ditandai sebagai Tafsir serentak. JP laporan sudah dihitung per sesi; aksi ini hanya merapikan penanda jurnal dan menyimpan audit.</p></div>
            <div class="overflow-x-auto"><table class="min-w-[1180px] w-full divide-y divide-slate-200 text-sm"><thead class="bg-amber-50 text-amber-950"><tr><th class="p-3 text-left">Tanggal / Jam</th><th class="p-3 text-left">Guru jadwal → efektif</th><th class="p-3 text-left">Kelas / Mapel</th><th class="p-3 text-right">Jurnal</th><th class="p-3 text-right">JP sebelum → sesudah</th><th class="p-3 text-left">Status</th><th class="p-3"></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($tafsirAuditRows as $row)<tr><td class="p-3 font-semibold">{{ \Carbon\Carbon::parse($row['date'])->translatedFormat('d F Y') }}<span class="block text-xs font-normal text-slate-500">{{ substr($row['starts_at'], 0, 5) }} - {{ substr($row['ends_at'], 0, 5) }}</span></td><td class="p-3">{{ $row['original_teacher_name'] }}<span class="block text-xs text-slate-500">Mengajar: {{ $row['effective_teacher_name'] }}</span></td><td class="p-3">{{ implode(', ', $row['classes']) }}<span class="block text-xs text-slate-500">{{ implode(', ', $row['subjects']) }}</span></td><td class="p-3 text-right">{{ $row['journal_count'] }}/{{ $row['expected_journal_count'] }}</td><td class="p-3 text-right">{{ $row['jp_before'] }} → {{ $row['jp_after'] }}</td><td class="p-3"><span class="rounded-full px-2 py-1 text-xs font-bold {{ $row['can_normalize'] ? 'bg-emerald-100 text-emerald-800' : ($row['can_revert'] ? 'bg-sky-100 text-sky-800' : 'bg-slate-100 text-slate-700') }}">{{ $row['status'] }}</span><span class="mt-1 block text-xs text-slate-500">Sesi tersimpan: {{ implode(', ', $row['original_sessions']) ?: '-' }}</span></td><td class="p-3 text-right">@if($row['can_normalize'])<form method="POST" action="{{ route('admin.monthly-jp-recap.tafsir-normalizations.store') }}">@csrf<input type="hidden" name="academic_term_id" value="{{ $report['term']->id }}"><input type="hidden" name="date" value="{{ $row['date'] }}"><input type="hidden" name="schedule_id" value="{{ $row['schedule_ids'][0] }}"><button class="rounded-xl bg-amber-600 px-3 py-2 text-xs font-black text-white hover:bg-amber-700" onclick="return confirm('Tandai jurnal kelompok ini sebagai Tafsir serentak? Riwayat audit akan disimpan.')">Setujui normalisasi</button></form>@elseif($row['can_revert'])<form method="POST" action="{{ route('admin.monthly-jp-recap.tafsir-normalizations.revert') }}">@csrf<input type="hidden" name="academic_term_id" value="{{ $report['term']->id }}"><input type="hidden" name="date" value="{{ $row['date'] }}"><input type="hidden" name="schedule_id" value="{{ $row['schedule_ids'][0] }}"><button class="rounded-xl bg-sky-700 px-3 py-2 text-xs font-black text-white hover:bg-sky-800" onclick="return confirm('Kembalikan penanda jurnal ke sesi asal? Riwayat audit tidak akan dihapus.')">Batalkan normalisasi</button></form>@endif</td></tr>@empty<tr><td colspan="7" class="p-5 text-center text-slate-500">Tidak ada jurnal Tafsir serentak pada periode ini.</td></tr>@endforelse</tbody></table></div>
        </section>
    </div>
</x-layouts.portal>
