<x-layouts.portal title="Detail Hasil Tasmi'" :portal-label="$portalLabel" :breadcrumb="$breadcrumb">
    <section class="mx-auto max-w-4xl space-y-6">
        <header class="portal-page-header"><a href="{{ $backUrl }}" class="inline-flex items-center gap-2 text-xs font-black text-emerald-800 hover:text-emerald-950"><span aria-hidden="true">←</span> {{ $backLabel }}</a><p class="mt-4 text-[11px] font-black uppercase tracking-[.16em] text-emerald-700">{{ $readOnly ? 'Data baca-saja' : 'Hasil Tasmi\'' }}</p><h1 class="mt-1 text-3xl font-black tracking-tight text-slate-950">Detail Hasil Tasmi'</h1><p class="mt-2 text-sm font-medium text-slate-500">Informasi setoran, pemeriksa, dan riwayat pencatatan.</p></header>

        <section class="ui-card overflow-hidden">
            <div class="border-b border-emerald-100 bg-emerald-50 px-5 py-5 sm:px-7"><p class="text-[11px] font-black uppercase tracking-[.14em] text-emerald-700">{{ $record->classroomTerm?->classroom?->name ?? $record->classroomTerm?->name ?? 'Kelas' }}</p><div class="mt-1 flex flex-wrap items-center justify-between gap-3"><h2 class="text-2xl font-black text-slate-950">{{ $record->student?->name ?? '-' }}</h2><span class="rounded-full bg-white px-3 py-1 text-sm font-black text-emerald-800 shadow-sm">{{ \App\Models\TasmiRecord::predicateLabel($record->predicate) }}</span></div><p class="mt-1 text-sm font-semibold text-slate-500">{{ $record->student?->nis ? 'NIS '.$record->student->nis : 'NIS tidak tersedia' }}</p></div>
            <dl class="divide-y divide-slate-100 px-5 sm:px-7">
                <div class="detail-row"><dt>Semester</dt><dd>{{ $record->academicTerm?->name ?? '-' }}</dd></div><div class="detail-row"><dt>Penguji / PJ Tasmi'</dt><dd>{{ $record->examinerTeacher?->name ?? '-' }}</dd></div><div class="detail-row"><dt>Jenis dan juz</dt><dd>{{ \App\Models\TasmiRecord::examTypeOptions()[$record->exam_type] ?? $record->exam_type }} · {{ $record->juz_range_label }}</dd></div><div class="detail-row"><dt>Tanggal ujian</dt><dd>{{ $record->exam_date?->locale('id')->translatedFormat('l, d F Y') ?? '-' }}{{ $record->hijri_date ? ' · '.$record->hijri_date : '' }}</dd></div><div class="detail-row"><dt>Label hari</dt><dd>{{ $record->exam_day_label ?: '-' }}</dd></div><div class="detail-row"><dt>Catatan</dt><dd class="whitespace-pre-line font-medium">{{ $record->notes ?: '-' }}</dd></div><div class="detail-row"><dt>Diinput</dt><dd>{{ $record->inputBy?->name ?? '-' }} · {{ $record->input_at?->timezone('Asia/Jakarta')->format('d M Y H:i') ?? '-' }} WIB</dd></div><div class="detail-row"><dt>Terakhir diperbarui</dt><dd>{{ $record->lastUpdatedBy?->name ?? $record->inputBy?->name ?? '-' }} · {{ $record->updated_at?->timezone('Asia/Jakarta')->format('d M Y H:i') ?? '-' }} WIB</dd></div>
            </dl>
        </section>

        <section class="ui-card p-5 sm:p-7"><p class="text-[11px] font-black uppercase tracking-[.14em] text-slate-400">Jejak pencatatan</p><h2 class="mt-1 text-xl font-black text-slate-900">Riwayat perubahan</h2><div class="mt-5 space-y-3">@forelse($auditLogs as $log)<article class="rounded-2xl border border-slate-100 bg-slate-50 px-4 py-3"><p class="text-sm font-black text-slate-800">{{ $log->reason === 'created_tasmi' ? 'Hasil Tasmi dibuat' : 'Hasil Tasmi diperbarui' }}</p><p class="mt-1 text-xs font-semibold text-slate-500">{{ $log->changer?->name ?? 'Sistem' }} · {{ $log->changed_at?->timezone('Asia/Jakarta')->format('d M Y H:i') ?? '-' }} WIB</p></article>@empty<p class="text-sm font-semibold text-slate-500">Belum ada riwayat perubahan tambahan.</p>@endforelse</div></section>
    </section>
</x-layouts.portal>
