<div class="fi-gq-notification" x-data="{ open: false, unread: 0, items: [], refresh() { fetch('{{ route('notifications.feed') }}', { headers: { Accept: 'application/json' } }).then((response) => response.json()).then((data) => { this.unread = data.unread_count || 0; this.items = data.notifications || []; }).catch(() => {}); } }" x-init="refresh(); setInterval(() => refresh(), 30000)">
    <button type="button" class="fi-gq-notification-toggle" @click="open = !open; if (open) refresh()" aria-label="Notifikasi" :aria-expanded="open.toString()">
        <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke-width="1.75" stroke="currentColor" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" /></svg>
        <span x-show="unread > 0" x-text="unread > 99 ? '99+' : unread" class="fi-gq-notification-badge"></span>
    </button>
    <section x-show="open" x-transition @click.outside="open = false" @keydown.escape.window="open = false" class="fi-gq-notification-panel" role="dialog" aria-label="Notifikasi">
        <header class="flex items-center justify-between border-b border-gray-200 px-4 py-3 dark:border-gray-800"><strong class="text-sm">Notifikasi</strong><button type="button" @click="fetch('{{ route('notifications.read-all') }}', { method: 'POST', headers: { 'X-CSRF-TOKEN': '{{ csrf_token() }}', Accept: 'application/json' } }).then(() => refresh())" class="font-mono text-[10px] font-bold underline decoration-primary-400 decoration-2 underline-offset-4">Tandai semua dibaca</button></header>
        <div class="max-h-96 overflow-y-auto">
            <template x-if="items.length === 0"><p class="px-5 py-8 text-center text-xs font-bold text-gray-400">Tidak ada notifikasi baru.</p></template>
            <template x-for="item in items" :key="item.id"><a :href="item.link_url || '#'" @click="fetch('{{ route('notifications.read', '__ID__') }}'.replace('__ID__', item.id), { method: 'POST', headers: { 'X-CSRF-TOKEN': '{{ csrf_token() }}', Accept: 'application/json' } }).catch(() => {})" class="fi-gq-notification-item"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-primary-100 text-xs font-black text-primary-800" x-text="item.severity === 'success' ? '✓' : item.severity === 'info' ? 'i' : '!'"></span><span class="min-w-0 flex-1"><span class="block text-xs font-bold" x-text="item.title"></span><span class="mt-1 block line-clamp-2 text-[11px] leading-4 text-gray-500" x-text="item.body"></span><span class="mt-1 block font-mono text-[10px] text-gray-400" x-text="item.created_at"></span></span><span x-show="item.status === 'unread'" class="mt-1 h-2 w-2 shrink-0 rounded-full bg-primary-500"></span></a></template>
        </div>
        <footer class="border-t border-gray-200 px-4 py-3 text-center dark:border-gray-800"><a href="{{ route('notifications.index') }}" class="font-mono text-[10px] font-bold underline decoration-primary-400 decoration-2 underline-offset-4">Lihat semua notifikasi →</a></footer>
    </section>
</div>
